import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import pg from 'pg';
import fs from 'fs';
import path from 'path';

const {Pool}=pg;
const app=express();
const port=process.env.PORT||3000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:false});
app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), geolocation=(), microphone=(self)');next()});
app.use(cors({origin:(process.env.ALLOWED_ORIGINS||'*').split(',').map(s=>s.trim()),credentials:false}));
app.use(express.json({limit:'1mb'}));

async function initDb(){await pool.query(fs.readFileSync(new URL('./schema.sql',import.meta.url),'utf8'))}
function sign(user){return jwt.sign({sub:user.id,email:user.email},process.env.JWT_SECRET,{expiresIn:'14d'})}
function auth(req,res,next){const h=req.headers.authorization||'',token=h.startsWith('Bearer ')?h.slice(7):null;if(!token)return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(token,process.env.JWT_SECRET);next()}catch{return res.status(401).json({error:'Invalid or expired session'})}}
const num=v=>Number(v||0);
const text=(v,max=120)=>String(v??'').trim().slice(0,max);
function money(v,label='Amount'){const n=Number(v);if(!Number.isFinite(n)||n<0||n>1e12)throw new Error(`${label} must be a valid non-negative number`);return n}
function bounded(v,min,max,label){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw new Error(`${label} must be between ${min} and ${max}`);return n}
function validDate(v,label='Date'){if(v===null||v===undefined||v==='')return null;const s=String(v).slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||Number.isNaN(Date.parse(s+'T00:00:00Z')))throw new Error(`${label} is invalid`);return s}
function validateRecord(table,x={}){
 if(table==='assets'){const name=text(x.name);if(!name)throw new Error('Asset name is required');return{name,category:text(x.category)||'Other',value:money(x.value,'Asset value')}}
 if(table==='debts'){const name=text(x.name);if(!name)throw new Error('Debt name is required');return{name,category:text(x.category)||'Other',balance:money(x.balance,'Balance'),apr:bounded(x.apr??0,0,100,'APR'),minimum_payment:money(x.minimum_payment,'Minimum payment')}}
 if(table==='goals'){const name=text(x.name);if(!name)throw new Error('Goal name is required');return{name,target_amount:money(x.target_amount,'Target amount'),current_amount:money(x.current_amount,'Current amount'),target_date:validDate(x.target_date,'Target date')}}
 if(table==='scenarios'){const name=text(x.name)||'Scenario',scenario_type=text(x.scenario_type,60)||'other',payload=x.payload&&typeof x.payload==='object'&&!Array.isArray(x.payload)?x.payload:{};return{name,scenario_type,payload}}
 throw new Error('Unsupported record type')
}

async function getDashboard(userId){
 const [p,a,d,b,g,s]=await Promise.all([
  pool.query('SELECT * FROM financial_profiles WHERE user_id=$1',[userId]),pool.query('SELECT * FROM assets WHERE user_id=$1 ORDER BY created_at',[userId]),pool.query('SELECT * FROM debts WHERE user_id=$1 ORDER BY apr DESC, created_at',[userId]),pool.query('SELECT * FROM budget_categories WHERE user_id=$1 ORDER BY sort_order,name',[userId]),pool.query('SELECT * FROM goals WHERE user_id=$1 ORDER BY created_at',[userId]),pool.query('SELECT * FROM scenarios WHERE user_id=$1 ORDER BY created_at DESC',[userId])]);
 const profile=p.rows[0]||{},assets=a.rows,debts=d.rows,budget=b.rows,totalAssets=assets.reduce((x,r)=>x+num(r.value),0),totalDebt=debts.reduce((x,r)=>x+num(r.balance),0),debtMinimums=debts.reduce((x,r)=>x+num(r.minimum_payment),0),planned=budget.reduce((x,r)=>x+num(r.planned),0),actual=budget.reduce((x,r)=>x+num(r.actual),0),takeHome=num(profile.monthly_take_home),gross=num(profile.monthly_gross_income),housing=num(profile.monthly_housing),essential=num(profile.monthly_essential_expenses),recurringDebt=Math.max(num(profile.monthly_debt_payments),debtMinimums),emergency=num(profile.emergency_savings),reserveBase=Math.max(1,housing+essential+recurringDebt),emergencyMonths=emergency/reserveBase,dti=gross>0?((housing+recurringDebt)/gross)*100:0,safeToSpend=Math.max(0,takeHome-planned),cashFlow=takeHome-(housing+essential+recurringDebt);
 let score=100;if(cashFlow<0)score-=35;else if(takeHome&&cashFlow/takeHome<.1)score-=20;else if(takeHome&&cashFlow/takeHome<.2)score-=10;if(dti>50)score-=30;else if(dti>43)score-=20;else if(dti>36)score-=10;if(emergencyMonths<1)score-=25;else if(emergencyMonths<3)score-=15;else if(emergencyMonths<6)score-=5;score=Math.max(0,Math.min(100,Math.round(score)));
 const moves=[];if(debts.some(x=>num(x.apr)>=20))moves.push('Prioritize high-interest revolving debt.');if(emergencyMonths<3)moves.push('Build your emergency reserve toward at least 3 months of core expenses.');if(planned>takeHome)moves.push('Your monthly budget plan exceeds take-home income. Reduce planned categories.');if(!moves.length)moves.push('Keep your savings plan automated and review spending weekly.');moves.push('Use Can I Afford It? before adding any new recurring payment.');moves.push('Review net worth and goal progress monthly.');
 return{profile,assets,debts,budget,goals:g.rows,scenarios:s.rows,metrics:{totalAssets,totalDebt,netWorth:totalAssets-totalDebt,debtMinimums,planned,actual,takeHome,cashFlow,dti:Number(dti.toFixed(1)),emergencyMonths:Number(emergencyMonths.toFixed(1)),safeToSpend,healthScore:score},nextMoves:moves.slice(0,3)};
}

function moneySnapshot(d){const m=d.metrics,p=d.profile||{};return `Monthly take-home: $${m.takeHome}. Monthly gross income: $${num(p.monthly_gross_income)}. Planned monthly budget: $${m.planned}. Actual monthly budget: $${m.actual}. Safe to spend: $${m.safeToSpend}. Net worth: $${m.netWorth}. Total assets: $${m.totalAssets}. Total debt: $${m.totalDebt}. Minimum debt payments: $${m.debtMinimums}. DTI shown by the app: ${m.dti}%. Emergency reserve: ${m.emergencyMonths} months. Health score: ${m.healthScore}/100. Credit score entered by user: ${p.credit_score||'not entered'}. Assets: ${d.assets.map(x=>`${x.name} $${x.value}`).join(', ')||'none entered'}. Debts: ${d.debts.map(x=>`${x.name} balance $${x.balance}, APR ${x.apr||0}%, minimum $${x.minimum_payment||0}`).join('; ')||'none entered'}. Goals: ${d.goals.map(x=>`${x.name}, target $${x.target_amount}, current $${x.current_amount}`).join('; ')||'none entered'}.`;}
const moneyGuideInstructions=snapshot=>`You are Money Guide, the personal financial decision assistant inside Money Command Center. Be conversational, concise, practical, and candid. Sound like a highly capable ChatGPT-style partner, not a banker, salesperson, or disclaimer machine. Use the user's saved Money Command Center data when it is relevant and never invent missing numbers. Clearly distinguish known values from estimates. Help with budgeting, cash flow, debt, goals, net worth, purchase affordability, tradeoffs, and planning. When discussing a purchase, consider the payment, total monthly ownership cost, cash-flow cushion, debt load, reserves, and opportunity cost. For investment, tax, legal, credit, insurance, or other regulated/high-stakes topics, provide educational information and make assumptions clear rather than pretending to be a licensed professional. Do not promise returns, approvals, tax outcomes, or credit-score changes. If one missing fact would materially change the answer, ask one useful follow-up question. Keep answers easy to scan with short paragraphs and occasional bullets when helpful.\n\nSAVED FINANCIAL SNAPSHOT:\n${snapshot}`;

app.get('/health',(req,res)=>res.json({ok:true,service:'money-command-center-api'}));
app.post('/api/auth/register',async(req,res)=>{const email=text(req.body?.email,254).toLowerCase(),password=String(req.body?.password||''),name=text(req.body?.name,100)||null;if(!email||!/^\S+@\S+\.\S+$/.test(email)||password.length<8||password.length>200)return res.status(400).json({error:'A valid email and password of 8-200 characters are required'});try{const hash=await bcrypt.hash(password,12),q=await pool.query('INSERT INTO users(email,password_hash,name) VALUES($1,$2,$3) RETURNING id,email,name,created_at',[email,hash,name]),user=q.rows[0];await pool.query('INSERT INTO financial_profiles(user_id) VALUES($1) ON CONFLICT DO NOTHING',[user.id]);const defaults=['Housing','Utilities & subscriptions','Food & household','Transportation','Debt payments','Lifestyle & fun','Savings & goals'];for(let i=0;i<defaults.length;i++)await pool.query('INSERT INTO budget_categories(user_id,name,sort_order) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[user.id,defaults[i],i]);res.status(201).json({token:sign(user),user})}catch(e){if(e.code==='23505')return res.status(409).json({error:'An account with that email already exists'});console.error(e);res.status(500).json({error:'Could not create account'})}});
app.post('/api/auth/login',async(req,res)=>{const email=text(req.body?.email,254).toLowerCase(),password=String(req.body?.password||''),q=await pool.query('SELECT * FROM users WHERE email=$1',[email]),user=q.rows[0];if(!user||!(await bcrypt.compare(password,user.password_hash)))return res.status(401).json({error:'Invalid email or password'});res.json({token:sign(user),user:{id:user.id,email:user.email,name:user.name,created_at:user.created_at}})});
app.get('/api/me',auth,async(req,res)=>{const q=await pool.query('SELECT id,email,name,created_at FROM users WHERE id=$1',[req.user.sub]);res.json(q.rows[0])});
app.get('/api/dashboard',auth,async(req,res)=>res.json(await getDashboard(req.user.sub)));
app.put('/api/profile',auth,async(req,res)=>{try{const x=req.body||{},credit=x.credit_score===null||x.credit_score===undefined||x.credit_score===''?null:bounded(x.credit_score,300,850,'Credit score'),q=await pool.query(`INSERT INTO financial_profiles(user_id,monthly_take_home,monthly_gross_income,monthly_housing,monthly_essential_expenses,monthly_debt_payments,emergency_savings,credit_score,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,now()) ON CONFLICT(user_id) DO UPDATE SET monthly_take_home=EXCLUDED.monthly_take_home,monthly_gross_income=EXCLUDED.monthly_gross_income,monthly_housing=EXCLUDED.monthly_housing,monthly_essential_expenses=EXCLUDED.monthly_essential_expenses,monthly_debt_payments=EXCLUDED.monthly_debt_payments,emergency_savings=EXCLUDED.emergency_savings,credit_score=EXCLUDED.credit_score,updated_at=now() RETURNING *`,[req.user.sub,money(x.monthly_take_home,'Monthly take-home'),money(x.monthly_gross_income,'Monthly gross income'),money(x.monthly_housing,'Monthly housing'),money(x.monthly_essential_expenses,'Essential expenses'),money(x.monthly_debt_payments,'Debt payments'),money(x.emergency_savings,'Emergency savings'),credit]);res.json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/budget',auth,async(req,res)=>{try{const rows=Array.isArray(req.body?.categories)?req.body.categories:[];if(rows.length>100)throw new Error('Too many budget categories');for(let i=0;i<rows.length;i++){const r=rows[i],name=text(r.name,100);if(!name)continue;await pool.query(`INSERT INTO budget_categories(user_id,name,planned,actual,sort_order) VALUES($1,$2,$3,$4,$5) ON CONFLICT(user_id,name) DO UPDATE SET planned=EXCLUDED.planned,actual=EXCLUDED.actual,sort_order=EXCLUDED.sort_order`,[req.user.sub,name,money(r.planned,'Planned amount'),money(r.actual,'Actual amount'),i])}res.json((await getDashboard(req.user.sub)).budget)}catch(e){res.status(400).json({error:e.message})}});
function crud(table,fields){
 app.post('/api/'+table,auth,async(req,res)=>{try{const clean=validateRecord(table,req.body),vals=fields.map(f=>clean[f]??null),placeholders=fields.map((_,i)=>'$'+(i+2)).join(','),q=await pool.query(`INSERT INTO ${table}(user_id,${fields.join(',')}) VALUES($1,${placeholders}) RETURNING *`,[req.user.sub,...vals]);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
 app.put('/api/'+table+'/:id',auth,async(req,res)=>{try{const clean=validateRecord(table,req.body),sets=fields.map((f,i)=>`${f}=$${i+1}`).join(','),vals=fields.map(f=>clean[f]??null),q=await pool.query(`UPDATE ${table} SET ${sets} WHERE id=$${fields.length+1} AND user_id=$${fields.length+2} RETURNING *`,[...vals,req.params.id,req.user.sub]);if(!q.rowCount)return res.status(404).json({error:'Record not found'});res.json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
 app.delete('/api/'+table+'/:id',auth,async(req,res)=>{const q=await pool.query(`DELETE FROM ${table} WHERE id=$1 AND user_id=$2`,[req.params.id,req.user.sub]);if(!q.rowCount)return res.status(404).json({error:'Record not found'});res.status(204).end()})
}
crud('assets',['name','category','value']);crud('debts',['name','category','balance','apr','minimum_payment']);crud('goals',['name','target_amount','current_amount','target_date']);crud('scenarios',['name','scenario_type','payload']);

app.get('/api/financial-data',auth,async(req,res)=>{const [accounts,tx,recurring]=await Promise.all([pool.query('SELECT * FROM financial_accounts WHERE user_id=$1 ORDER BY created_at',[req.user.sub]),pool.query('SELECT * FROM transactions WHERE user_id=$1 ORDER BY posted_date DESC, created_at DESC LIMIT 250',[req.user.sub]),pool.query('SELECT * FROM recurring_items WHERE user_id=$1 AND active=true ORDER BY next_expected_date NULLS LAST, merchant_name',[req.user.sub])]);const spend30=tx.rows.filter(x=>!x.excluded&&!x.pending&&Number(x.amount)>0&&new Date(x.posted_date)>=new Date(Date.now()-30*86400000)).reduce((s,x)=>s+Number(x.amount),0);res.json({accounts:accounts.rows,transactions:tx.rows,recurring:recurring.rows,summary:{accountBalance:accounts.rows.filter(x=>!x.is_hidden).reduce((s,x)=>s+Number(x.current_balance||0),0),spendLast30Days:Number(spend30.toFixed(2)),connected:false,note:'Provider connection is not enabled yet; this API is the provider-ready financial data foundation.'}})});
app.post('/api/financial-data/accounts',auth,async(req,res)=>{try{const x=req.body||{},name=text(x.name);if(!name)throw new Error('Account name is required');const q=await pool.query(`INSERT INTO financial_accounts(user_id,name,official_name,account_type,account_subtype,mask,current_balance,available_balance,currency,is_hidden,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,now()) RETURNING *`,[req.user.sub,name,text(x.official_name,160)||null,text(x.account_type,50)||'other',text(x.account_subtype,60)||null,text(x.mask,8)||null,money(x.current_balance,'Current balance'),x.available_balance===null||x.available_balance===undefined||x.available_balance===''?null:money(x.available_balance,'Available balance'),text(x.currency,3).toUpperCase()||'USD',Boolean(x.is_hidden)]);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/financial-data/accounts/:id',auth,async(req,res)=>{try{const x=req.body||{},name=text(x.name);if(!name)throw new Error('Account name is required');const q=await pool.query(`UPDATE financial_accounts SET name=$1,official_name=$2,account_type=$3,account_subtype=$4,mask=$5,current_balance=$6,available_balance=$7,currency=$8,is_hidden=$9,updated_at=now() WHERE id=$10 AND user_id=$11 RETURNING *`,[name,text(x.official_name,160)||null,text(x.account_type,50)||'other',text(x.account_subtype,60)||null,text(x.mask,8)||null,money(x.current_balance,'Current balance'),x.available_balance===null||x.available_balance===undefined||x.available_balance===''?null:money(x.available_balance,'Available balance'),text(x.currency,3).toUpperCase()||'USD',Boolean(x.is_hidden),req.params.id,req.user.sub]);if(!q.rowCount)return res.status(404).json({error:'Account not found'});res.json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/financial-data/accounts/:id',auth,async(req,res)=>{const q=await pool.query('DELETE FROM financial_accounts WHERE id=$1 AND user_id=$2',[req.params.id,req.user.sub]);if(!q.rowCount)return res.status(404).json({error:'Account not found'});res.status(204).end()});
app.post('/api/financial-data/transactions',auth,async(req,res)=>{try{const x=req.body||{},name=text(x.name,180);if(!name)throw new Error('Transaction name is required');const amount=Number(x.amount);if(!Number.isFinite(amount)||Math.abs(amount)>1e12)throw new Error('Transaction amount is invalid');const q=await pool.query(`INSERT INTO transactions(user_id,account_id,posted_date,authorized_date,merchant_name,name,amount,category,pending,recurring,excluded,notes,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,now()) RETURNING *`,[req.user.sub,x.account_id||null,validDate(x.posted_date,'Posted date'),validDate(x.authorized_date,'Authorized date'),text(x.merchant_name,160)||null,name,amount,text(x.category,100)||null,Boolean(x.pending),Boolean(x.recurring),Boolean(x.excluded),text(x.notes,500)||null]);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/financial-data/transactions/:id',auth,async(req,res)=>{try{const x=req.body||{},name=text(x.name,180);if(!name)throw new Error('Transaction name is required');const amount=Number(x.amount);if(!Number.isFinite(amount)||Math.abs(amount)>1e12)throw new Error('Transaction amount is invalid');const q=await pool.query(`UPDATE transactions SET account_id=$1,posted_date=$2,authorized_date=$3,merchant_name=$4,name=$5,amount=$6,category=$7,pending=$8,recurring=$9,excluded=$10,notes=$11,updated_at=now() WHERE id=$12 AND user_id=$13 RETURNING *`,[x.account_id||null,validDate(x.posted_date,'Posted date'),validDate(x.authorized_date,'Authorized date'),text(x.merchant_name,160)||null,name,amount,text(x.category,100)||null,Boolean(x.pending),Boolean(x.recurring),Boolean(x.excluded),text(x.notes,500)||null,req.params.id,req.user.sub]);if(!q.rowCount)return res.status(404).json({error:'Transaction not found'});res.json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/financial-data/transactions/:id',auth,async(req,res)=>{const q=await pool.query('DELETE FROM transactions WHERE id=$1 AND user_id=$2',[req.params.id,req.user.sub]);if(!q.rowCount)return res.status(404).json({error:'Transaction not found'});res.status(204).end()});

app.post('/api/money-guide/chat',auth,async(req,res)=>{
 if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:'Money Guide is not connected yet.'});
 const message=String(req.body?.message||'').trim();if(!message)return res.status(400).json({error:'Message is required'});if(message.length>6000)return res.status(400).json({error:'Message is too long'});
 try{
  const d=await getDashboard(req.user.sub),snapshot=moneySnapshot(d),history=Array.isArray(req.body?.history)?req.body.history.slice(-12):[];
  const transcript=history.filter(x=>x&&['user','assistant'].includes(x.role)&&typeof x.text==='string').map(x=>`${x.role==='user'?'User':'Money Guide'}: ${x.text.slice(0,2500)}`).join('\n\n');
  const input=`${transcript?`CONVERSATION SO FAR:\n${transcript}\n\n`:''}USER'S NEW MESSAGE:\n${message}`;
  const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.MONEY_GUIDE_MODEL||'gpt-5.6-luna',instructions:moneyGuideInstructions(snapshot),input,max_output_tokens:1200})});
  const data=await r.json().catch(()=>({}));if(!r.ok)return res.status(502).json({error:data?.error?.message||'Money Guide could not answer right now.'});
  const out=(data.output_text||data.output?.flatMap(o=>o?.content||[]).filter(c=>c?.type==='output_text'&&c?.text).map(c=>c.text).join('\n')||'').trim();
  if(!out)return res.status(502).json({error:'Money Guide returned an empty response.'});res.json({text:out});
 }catch(e){console.error('Money Guide chat error',e);res.status(500).json({error:'Money Guide could not answer right now.'})}
});

app.post('/api/money-guide/live-session',auth,async(req,res)=>{
 if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:'Money Guide voice is ready, but the OpenAI API key still needs to be connected.'});
 try{
  const d=await getDashboard(req.user.sub),snapshot=moneySnapshot(d);
  const session={type:'realtime',model:'gpt-realtime-1.5',output_modalities:['audio'],instructions:moneyGuideInstructions(snapshot)+'\n\nFor this voice session, use natural American conversational cadence, short acknowledgments, and fairly short spoken answers unless the user asks for depth.',audio:{output:{voice:'marin'}}};
  const r=await fetch('https://api.openai.com/v1/realtime/client_secrets',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({session})}),data=await r.json().catch(()=>({}));
  if(!r.ok)return res.status(502).json({error:data?.error?.message||'Could not start Money Guide voice.'});const value=data?.value||data?.client_secret?.value;if(!value)return res.status(502).json({error:'OpenAI did not return a live-session token.'});res.json({value,expires_at:data?.expires_at||data?.client_secret?.expires_at||null});
 }catch(e){console.error(e);res.status(500).json({error:'Could not start Money Guide voice.'})}
});

const mobileCss=`<style id="mobile-layout-fix">@media(max-width:920px){html,body{max-width:100%;overflow-x:hidden}.wrap{max-width:none!important;width:100%!important;padding:14px!important}.appShell{display:block!important}.side{position:static!important;width:100%!important;margin-bottom:14px!important;padding:14px!important}.nav{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important;overflow:visible!important;padding:0!important}.nav button{width:100%!important;text-align:center!important;white-space:normal!important;min-height:44px!important;padding:10px 8px!important}main{min-width:0!important;width:100%!important}.grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.grid2{grid-template-columns:1fr!important}.card{padding:16px!important;border-radius:16px!important}.table{display:block!important;width:100%!important;overflow-x:auto!important;-webkit-overflow-scrolling:touch!important}}@media(max-width:620px){.wrap{padding:10px!important}.auth{margin:18px auto!important;padding:18px!important}.topbar{align-items:flex-start!important;gap:10px!important}.sectionTitle{font-size:24px!important;line-height:1.15!important}.grid,.grid2{grid-template-columns:1fr!important}.metric{font-size:25px!important;overflow-wrap:anywhere!important}.row{display:block!important}.field{min-width:0!important;width:100%!important;margin-top:10px!important}input,select,textarea{font-size:16px!important}button{min-height:44px}.split{align-items:flex-start!important;flex-direction:column!important}.split>button{width:100%!important}.nav{grid-template-columns:1fr 1fr!important}.nav button{font-size:13px!important}.item{padding:12px!important}.bigcallout{padding:16px!important}.card h2{font-size:20px!important;margin-top:0}.card h3{font-size:17px!important}#logout{margin-top:12px!important}}@media(max-width:380px){.nav{grid-template-columns:1fr!important}.topbar{display:block!important}.topbar .pill{margin-top:8px!important}}</style>`;
function sendApp(req,res){const file=path.join(process.cwd(),'public','index.html');let html=fs.readFileSync(file,'utf8');html=html.replace('</head>',mobileCss+'\n<link rel="stylesheet" href="/ux.css?v=6">\n</head>');html=html.replace('</body>','<script src="/ux.js?v=6"></script>\n<script src="/money-voice.js?v=5"></script>\n<script src="/product-upgrades.js?v=2"></script>\n</body>');res.type('html').send(html)}
app.get('/',sendApp);app.use(express.static(path.join(process.cwd(),'public'),{index:false}));app.get('*',(req,res,next)=>{if(req.path.startsWith('/api/')||req.path==='/health')return next();sendApp(req,res)});app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Unexpected server error'})});
initDb().then(()=>app.listen(port,'0.0.0.0',()=>console.log(`Money Command Center API listening on ${port}`))).catch(e=>{console.error('DB init failed',e);process.exit(1)});